### ISSUE TITLE
Question on gas costs

### ISSUE THREAD

**Issue by parkerburchett** [bancorprotocol/carbon-contracts#67]
Is there a doc somewhere with some estimated gas costs for trades and deploying new strategies?

**Comment by yudilevi** [comment]
Hey,

There's no doc but I can give you a quick breakdown based on some tests:
- Strategy creation: average of 160K
- Trade - varies, the range is 120k-350k

For trades, the range is generally pretty wide as it depends on the number of strategies the trade goes through, and the implementation of the tokens themselves (some tokens have more expensive transfer calls).
The average above is based on trading through 1 to 10 strategies which should be more than enough with big enough strategies - we'll need to wait and see what the real average is though.

Yudi

**Comment by parkerburchett** [comment]
Thanks!

**Comment by parkerburchett** [comment]
Following up here for other people looking for gas costs. 

Here's a `tradeByTargetAmount` that only touched one strategy that used 162k gas https://etherscan.io/tx/0x2d1cfc4643dddd098f4788804cf8c22163fbfa5cfd6b3da6bd184a81950b9b94

**Comment by yudilevi** [comment]
Yup, as I mentioned above, the costs can vary between different tokens.

**Comment by barakman** [comment]
Each one of the two tokens involved here adds a bunch of stuff executed as part of the standard ERC20 operations.

Specifically in the context of this transaction, as part of `transfer` and `transferFrom`.

USDC is upgradable, hence every function call to that Token contract goes through a Proxy contract.

PEPE implements a `_beforeTokenTransfer` function which is called inside `transfer` and `transferFrom`.

Subsequently, every trade on this strategy includes a bunch of additional storage read operations AND external function calls, which are the 2nd and 3rd most expensive ops in Ethereum (preceded only by storage write operations).

Another thing which may impact the gas cost in this specific case (though it should become significant proportionally to the number of strategies being traded on), is the "large difference" between USDC and PEPE, which stems from the extremely low market price of PEPE vs USDC, combined with the many more decimals in PEPE vs USDC (18 vs 6).

This leads to extremely large values stored in each strategy, which in turn lead to more expensive calculation during each trade (internal contract functions `mulDivF` and `mulDivC` running in full).
